[package]
name = "rust-common-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
im = "15.0.0"
alloy-rlp = "0.3.16"
alloy-primitives = { version = "1.6.1", features = ["rlp"] }
rayon = "1.11.0"
quick_cache = { path = "../../quick-cache" }

[dev-dependencies]
foyer-memory = "0.22.4"
moka = { version = "0.12.16", features = ["sync"] }

[[bench]]
name = "cache_comparison"
harness = false
